version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${NAME_OS}
      - POSTGRES_USER=${USER_OS}
      - POSTGRES_PASSWORD=${PASSWORD_OS}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "alembic upgrade head && python3 -m main"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=${NAME_OS}
      - POSTGRES_USER=${USER_OS}
      - POSTGRES_PASSWORD=${PASSWORD_OS}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    env_file:
      - .env