"""add others table

Revision ID: d7d393d2aaf2
Revises: 8c69f9246dc5
Create Date: 2023-12-06 21:53:03.502973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d393d2aaf2'
down_revision: Union[str, None] = '8c69f9246dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CheckListAuto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rele_type', sa.String(length=120), nullable=True),
    sa.Column('qtd_rele', sa.Integer(), nullable=True),
    sa.Column('qtd_cable', sa.Integer(), nullable=True),
    sa.Column('switch_type', sa.String(length=120), nullable=True),
    sa.Column('qtd_switch', sa.Integer(), nullable=True),
    sa.Column('qtd_hub', sa.Integer(), nullable=True),
    sa.Column('other_equipament', sa.String(), nullable=True),
    sa.Column('file_budget', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CheckListAuto_id'), 'CheckListAuto', ['id'], unique=False)
    op.create_table('CheckListCam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qtd_cam', sa.Integer(), nullable=True),
    sa.Column('qtd_box_cable', sa.Integer(), nullable=True),
    sa.Column('qtd_rca', sa.Integer(), nullable=True),
    sa.Column('qtd_p4', sa.Integer(), nullable=True),
    sa.Column('qtd_dvr', sa.Integer(), nullable=True),
    sa.Column('qtd_hd', sa.Integer(), nullable=True),
    sa.Column('hds_size', sa.Integer(), nullable=True),
    sa.Column('other_equipament', sa.String(), nullable=True),
    sa.Column('file_budget', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CheckListCam_id'), 'CheckListCam', ['id'], unique=False)
    op.create_table('CheckListSound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qtd_sound_box', sa.Integer(), nullable=True),
    sa.Column('qtd_cable', sa.Integer(), nullable=True),
    sa.Column('qtd_conn', sa.Integer(), nullable=True),
    sa.Column('qtd_ampli', sa.Integer(), nullable=True),
    sa.Column('qtd_receiver', sa.Integer(), nullable=True),
    sa.Column('other_equipament', sa.String(), nullable=True),
    sa.Column('file_budget', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CheckListSound_id'), 'CheckListSound', ['id'], unique=False)
    op.create_table('ClientAdress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(length=140), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('name_building', sa.String(length=120), nullable=True),
    sa.Column('reference_point', sa.String(length=340), nullable=True),
    sa.Column('complement', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ClientAdress_id'), 'ClientAdress', ['id'], unique=False)
    op.create_table('Constructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Constructions_id'), 'Constructions', ['id'], unique=False)
    op.create_table('OsConstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('scheduling', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('sale', sa.String(), nullable=True),
    sa.Column('signature_emplooye', sa.String(length=120), nullable=True),
    sa.Column('signature_client', sa.String(length=120), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OsConstructions_id'), 'OsConstructions', ['id'], unique=False)
    op.create_table('OsMaintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('scheduling', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('sale', sa.String(), nullable=True),
    sa.Column('signature_emplooye', sa.String(length=120), nullable=True),
    sa.Column('signature_client', sa.String(length=120), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OsMaintenance_id'), 'OsMaintenance', ['id'], unique=False)
    op.create_table('OtherCheckList',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('file_budget', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
